### ISSUE TITLE
Use frictionless as input format for metadata

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/deposits#28]

**Comment by mpadge** [comment]
This isn't really going to work, because frictionless metadata are entirely about the internal structure of data sets. In contrast, the metadata needed by deposits include identifiers used to inter-relate different deposits. They enable hierarchical inter-relationships between deposits, which is a critically important component here. There are also frictionless datapackages, but they primarily serve to encode (and enable the encoding of) systems to apply and validate a single expected representation across a suite of invididual data packages, yet without any internal way to represent relationships between those packages.

**Comment by noamross** [comment]
Can you give an example of why that wouldn't work in adding this additional data to the data packages metadata?

**Comment by mpadge** [comment]
Yeah, right, there is actually no reason why it wouldn't work; it just has to be all hand-coded from scratch. I'll document current mechanism here to understand steps needed to drop current `atom4R` metadata system in favour of `frictionless`.

## Initial metadata contruction

``` r
library (deposits)
service <- "zenodo"
metadata <- list (
    Title = "Iris Dataset",
    abstract = "This is the abstract",
    Creator = list ("Edgar Anderson"),
    Publisher = "American Iris Society",
    Source = "https://doi.org/10.1111/j.1469-1809.1936.tb02137.x",
    Language = "eng"
)
cli <- depositsClient$new (service, sandbox = TRUE, metadata = metadata)
```
That fills metadata with these calls:
``` r
cli$metadata <- validate_metadata (metadata, service)
# The conversion is achieved via:
metadata <- metadata_to_dcmi (metadata)
```

That function works by writing metadata to a temporary `.json` file and reading it back in via `atom4R`:
``` r
filename <- tempfile (pattern = "meta_", fileext = ".json")
deposits_metadata_template (filename, metadata)
head (readLines (filename))
#> [1] "{"                                                                                                 
#> [2] "  \"_comment1\": \"Fields starting with underscores will be ignored (and can safely be deleted)\","
#> [3] "  \"Abstract\": \"This is the abstract\","                                                         
#> [4] "  \"AccessRights\": \"\","                                                                         
#> [5] "  \"AccrualMethod\": \"\","                                                                        
#> [6] "  \"AccrualPeriodicity\": \"\","
```
The contents of that file are then read and converted via:
``` r
metadata <- deposits_meta_to_dcmi (filename)
metadata
#> <DCEntry>
#> ....|-- updated: 2022-11-15 12:02:03
#> ....|-- title <DCTitle>
#> ........|-- value: Iris Dataset
#> ....|-- source <DCSource>
#> ........|-- value: https://doi.org/10.1111/j.1469-1809.1936.tb02137.x
#> ....|-- abstract <DCAbstract>
#> ........|-- value: This is the abstract
#> ....|-- creator <DCCreator>
#> ........|-- value: Edgar Anderson
#> ....|-- language <DCLanguage>
#> ........|-- value: eng
#> ....|-- publisher <DCPublisher>
#> ........|-- value: American Iris Society
```

That works by starting a template as an empty list of all entries returned by:
``` r
meta_terms <- dcmi_terms ()
print (meta_terms)
#>  [1] "Abstract"              "AccessRights"          "AccrualMethod"        
#>  [4] "AccrualPeriodicity"    "AccrualPolicy"         "Alternative"          
#>  [7] "Audience"              "Available"             "BibliographicCitation"
#> [10] "ConformsTo"            "Contributor"           "Coverage"             
#> [13] "Created"               "Creator"               "Date"                 
#> [16] "DateAccepted"          "DateCopyrighted"       "DateSubmitted"        
#> [19] "Description"           "EducationalLevel"      "Extent"               
#> [22] "Format"                "HasPart"               "HasVersion"           
#> [25] "Identifier"            "InstructionalMethod"   "IsPartOf"             
#> [28] "IsReferencedBy"        "IsReplacedBy"          "IsRequiredBy"         
#> [31] "Issued"                "IsVersionOf"           "Language"             
#> [34] "License"               "Mediator"              "Medium"               
#> [37] "Modified"              "Provenance"            "Publisher"            
#> [40] "References"            "Relation"              "Replaces"             
#> [43] "Requires"              "Rights"                "RightsHolder"         
#> [46] "Source"                "Spatial"               "Subject"              
#> [49] "TableOfContents"       "Temporal"              "Title"                
#> [52] "Type"                  "Valid"
```
The main function then loops over all terms in `metadata` parameter, and fills the corresponding values in the `meta_terms` list. The resultant list is then written to `filename`, read back in via `jsonlite`, and each term stored in an `atom4R` object with `do.call` to the matching `add<TERM>` method.

## Steps needed to adapt to frictionless

- Replace current initially empty `.json` template with proforma datapackage template from `frictionless`
- Re-define DCMI terms separate from current definition via `atom4R`
- Remove all of the `atom4R`-specific processing lines

## What is lost?

- `atom4R` has its own internal validation mechanisms to ensure compliance with DCMI terms

## Why that matters?

One argument might be that it doesn't actually matter. Frictionless itself enforces no standardisation, and allows entirely arbitrary fields to be defined in any `.json` file. But the strong counter-argument is that standardisation provides the best basis for inter-relating different deposits, including relating, or even moving, deposits between different deposition services. Since that kind of functionality forms an important motivation of this whole endeavour, and was indeed a key component of the original R Consortium project, it seems unwise to simply discard it now. Conclusion: Standardisation should be retained, and all the reasons for originally selecting DCMI and the core schema still apply.

## What needs to be done to regain lost functionality

- Encode an internal DCMI validation routine for the metadata to replace currently functionality off-loaded to `atom4R`.

**Comment by mpadge** [comment]
## Next steps: Initiation of a deposit

The first step in current deposit initiation is to convert the current `atom4R` metadata to a simple list, so frictionless would make that more straightforard :heavy_check_mark: 

The second step is an additional validation routine, to confirm that the terms specified are actually valid for the specified deposits service. These rely on service-specific files like [`metadata-validate-zenodo.R`](https://github.com/ropenscilabs/deposits/blob/main/R/metadata-validate-zenodo.R), which compare the vocabularies defined in [the internal data files](https://github.com/ropenscilabs/deposits/tree/main/inst/extdata) using mechanisms that could be used exactly as is without any modification :heavy_check_mark: 

The actual call then returns a list full of service-specific (meta)data such as URLs and DOIs. These are currently used to fill the `hostdata` component of the client, and to re-populate the local metadata. That metadata component is then written to a local XML file and uploaded, just like a `frictionless.yml` file.

That is then the only major component of the initiation of a new deposit which would need extensive adapation. The current scheme has a few shortcomings anyway, like the iteration of host retrieval -> metadata re-population -> upload -> second round of retrieval -> final metadata re-population.

**Comment by mpadge** [comment]
All of the above commits remove the `atom4R` dependency, and convert all metadata representations to direct lists, with `jsonlite` then the only tool to read/write metadata.

## TODO

- [ ] Restructure the internal `metadata` object so it represents DCMI entities only.
- [ ] Then implement separate metadata translation functions for each service, by using the `term_map` tables to convert the DCMI representations to service-specific forms.
- [ ] Document this internal metadata wrangling procedure, at least internally, and maybe as a vignette.

So conversion to service-specific forms is only ever a temporary procedure, and the converted representations will not be stored anywhere within the client.

**Comment by mpadge** [comment]
That doesn't yet directly use frictionless, but everything from the above commit is now ready to do so. All metadata are lists, and `atom4R` is no longer used at all. The metadata scheme can incorporate frictionless simply by inserting the frictionless data within the current metadata lists, and the in/out routines for json files will work just the same.

**Comment by mpadge** [comment]
The above commit uploads the frictionless metadata along with standard `deposit_upload_file()` call.

## TODO

- [ ] When client connected to existing deposit and new data are to be uploaded, then download metadata and update with new deposit info before re-uploading.
- [ ] Allow frictionless data to hold multiple "resources"
- [ ] Change currently uploaded metadata in DCMI format to host-specific format, so that services recognise and use metadata.

**Comment by mpadge** [comment]
Finally closing this issue. One point from above is left unchecked, but it's really a separate issue, so addressed via #39.

**Comment by mpadge** [comment]
Re-opening for one minor tweak. If local "datapackage.json" has multiple resources, then any upload action that does not complete all resources listed there should issue a reminder of the discrepancy between actual uploaded resources and those list ed in "datapackage".

**Comment by noamross** [comment]
🎉 Thanks for all the good work on this! I appreciate it was a major turn for the package but I think it'll be a great workflow.

**Comment by mpadge** [comment]
Yes indeed, it really does make not only the workflow, but future package maintenance, so much smoother and easier. It was a great idea after all :rocket:
