### ISSUE TITLE
Convert DCMI metadata to host-specific form prior to upload

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/deposits#39]
## DONE:

- [x] Develop system for generalising the representation of metadata structures
- [x] Develop system for generalising translation between metadata structures
- [x] Use that to change currently uploaded metadata in DCMI format to host-specific format, so that services recognise and use metadata.
- [x] Clean up all primary routines to remove unused service-specific code

## TODO:

nothing else

**Comment by mpadge** [comment]
> 
>     * [ ]  Develop system for generalising the representation of metadata structures.
> 
> 
That is now [json-schemas](https://json-schema.org/), for which I made [this "jsonschema" repo](https://github.com/mpadge/jsonschema). It's around 100 times faster than [`ropensci/jsonvalidate`](https://docs.ropensci.org/jsonvalidate/), and more customisable and flexible, which is going to be important here. But ... It bundles [this C++ library for json parsing](https://github.com/pboettch/json-schema-validator) which includes code which is not CRAN-compliant. In particular, it uses a lot of pragmas to suppress various kinds of compiler warnings, and such suppression is not accepted on CRAN. Yet removing those generates a heap of warnings, which is also not acceptible on CRAN...

So after all of that work, it might be necessary, at least for now, to revert to using `jsonvalidate` instead.

**Comment by mpadge** [comment]
>     * [ ]  Develop system for generalising translation between metadata structures
> 

This seems like one of the best candidates: https://www.mdpi.com/2076-3417/11/24/11978

**Comment by mpadge** [comment]
All done now. The name of this issue is a misnomer, as most of the above commits served to restructure the entire way that both DCMI and scheme-specific metadata are represented, translated, and validated. It's now all done via the json schemas in [`inst/extdata`](https://github.com/ropenscilabs/deposits/tree/main/inst/extdata), with the codebase being almost entirely general, and free of service-specific routines.

One final

## TODO:

- [ ] Clean up all primary routines to remove unused service-specific code
