### ISSUE TITLE
Update docs for new frictionless workflow

### ISSUE THREAD

**Issue by noamross** [ropenscilabs/deposits#40]
README and vignettes will need to be updated to reflect the frictionless approach.  Better to to this sooner than later so we can get some more folks informally testing/contributing.

**Comment by mpadge** [comment]
Prior to that:

## TODO:

- [ ] Allow a frictionless-less workflow, by by-passing all frictionless stuff whenever `frictionless::add_resource()` errors (on anything that can't be parsed as a rectangular text file).

That will allow the broader, initial docs to remain general, before moving quickly on to a "frictionless workflows" section declaring that deposits is primarily intended to be work with frictionless.

**Comment by mpadge** [comment]
This should be the last point here:

## TODO

- [ ] Write new vignette on the frictionless workflow, including demonstrations of how to locally edit the "datapackage.json" file, and update remote version.

**Comment by mpadge** [comment]
Nope, one more point to go along with that:

## TODO

- [ ] Add new `deposit_update_frictionless()` function to allow client metadata to be directly edited, and changes propagated through to local and remote versions of "datapackage.json"

**Comment by mpadge** [comment]
Should now be very final:

## TODO:

- [ ] Add tests for new `deposit_update_frictionless()` method

**Comment by mpadge** [comment]
Done
